//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileTools.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\s*(?&lt;month&gt;\d+)\s*/\s*(?&lt;day&gt;\d+)(\s*/\s*(?&lt;year&gt;\d+)(\s+(?&lt;hour&gt;\d+)\s*\:\s*(?&lt;minute&gt;\d+)(\s*\:\s*(?&lt;second&gt;\d+)(\s*\.\s*(?&lt;millisecond&gt;\d+)){0,1}){0,1}){0,1}){0,1}\s*$.
        /// </summary>
        internal static string rxDateMDY {
            get {
                return ResourceManager.GetString("rxDateMDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\s*(?&lt;year&gt;\d{4})(?&lt;month&gt;\d{2})(?&lt;day&gt;\d{2})(\.(?&lt;hour&gt;\d{2})(?&lt;minute&gt;\d{2})((?&lt;second&gt;\d{2})((?&lt;millisecond&gt;\d{3})){0,1}){0,1}){0,1}\s*$.
        /// </summary>
        internal static string rxDateYYYYMMDD {
            get {
                return ResourceManager.GetString("rxDateYYYYMMDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;field&gt;\{(?&lt;name&gt;[^\}]+)\}).
        /// </summary>
        internal static string rxEmbeddedFieldName {
            get {
                return ResourceManager.GetString("rxEmbeddedFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?s:line\s+(?&lt;line&gt;\d+).*?position\s+(?&lt;position&gt;\d+))).
        /// </summary>
        internal static string rxJsonErrorLinePosition {
            get {
                return ResourceManager.GetString("rxJsonErrorLinePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;value&gt;-{0,1}\d+(\.\d+){0,1}).
        /// </summary>
        internal static string rxNumericalFloat {
            get {
                return ResourceManager.GetString("rxNumericalFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;value&gt;-{0,1}\d+).
        /// </summary>
        internal static string rxNumericalInt {
            get {
                return ResourceManager.GetString("rxNumericalInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?&lt;pre&gt;.*?)(?&lt;seed&gt;\d+)(?&lt;post&gt;.*)$.
        /// </summary>
        internal static string rxNumericalSeed {
            get {
                return ResourceManager.GetString("rxNumericalSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command-line tool suite for working with files.
        ///
        ///Syntax:
        ///FileTools.exe /action:{ActionName}
        ///    [/configfile:{Filename}]
        ///    [/input:{Filename|FolderName}]
        ///    [/output:{Filename|FolderName}]
        ///    [/pattern:{Pattern}]
        ///    [/infolder:{FolderName}] [/outfolder:{FolderName}]
        ///    [/infile:{Filename}] [/outfile:{Filename}]
        ///    [/option:{OptionName[,OptionValue]}]
        ///    [/range:{Start},{End}] [/base:{Base}]
        ///    [/digits:{Digits}] [/count:{Count}] [/datetime:{DateTime}]
        ///    [/text:{Text}]
        ///    [/prefix]  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
    }
}
